# Generated by Django 6.0 on 2025-12-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_student_roll_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
